# .gitlab-ci.yml

<<<<<<< HEAD
sync_from_github:
  stage: deploy
  image: alpine/git:latest

  script:
    - echo "Starting sync from GitHub..."

    # Source GitHub repository URL.
    - GITHUB_REPO_URL="https://github.com/whiteout-project/bot.git"

    # Clone the source repository from GitHub as a mirror.
    - git clone --mirror $GITHUB_REPO_URL .

    # Set the push URL to the current GitLab project.
    - git remote set-url --push origin "https://${CI_REGISTRY_USER}:${CI_JOB_TOKEN}@${CI_PROJECT_URL#https://}.git"

    # Push the mirror to the GitLab repository.
    - echo "Pushing mirror to GitLab at ${CI_PROJECT_URL}..."
    - git push --mirror origin

    - echo "Sync complete."

  rules:
    # Run ONLY when triggered by a webhook.
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
=======
test_job:
  stage: test
  image: python:3.12-slim # The Docker executor will pull this image
  tags:
    - docker # Ensure job is picked up by the runner
    - linux
  script:
    - echo "This job is running on a runner tagged with 'docker' and 'linux'."
    - echo "All my outbound internet traffic (like 'apt install' or 'pip install') goes through the WARP Gateway."
    - apt-get update && apt-get install -y curl
    - curl https://www.cloudflare.com/cdn-cgi/trace | grep warp
    - python3 --version
>>>>>>> 9feb4b6e78a2e86acd99edd93a2f4501a307fedf
