name: Build and Push Docker Image

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "existing release tag (e.g. v1.0.0)"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          context: docker
          file: docker/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm
          tags: |
            ghcr.io/${{ github.repository_owner }}/bot:latest
            ghcr.io/${{ github.repository_owner }}/bot:${{ github.event.inputs.tag || github.event.release.tag_name }}