name: Test Deployment

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.py'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.py'
  release:
    types: [ "published" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12.x", "3.13.x"]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Setup python environments
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install script dependencies
      run: python3 main.py --autoupdate

    - name: Write bot token
      run: echo "${{ secrets.CI_BOT_TOKEN }}" > bot_token.txt
    
    - name: Run script and wait for activation message
      run: |
        python3 main.py --autoupdate | while read -r line; do
          echo "$line"
          if [[ "$line" == *"Logged in as CI Bot#9154"* ]]; then
            echo "Bot is logged in, waiting 15 sec before ending test..."
            sleep 15
            break
          fi
        done

    - name: Check for Ddddocr solver initialization
      run: |
        sleep 10 # Give the OCR time to start
        cat log/gift_solver.txt || echo "log/gift_solver.txt not found or empty."
        if ! grep -q "DdddOcr test classification successful" log/gift_solver.txt; then
          echo "Required ddddocr test message not found in log/gift_solver.txt. Failing the job."
          exit 1
        else
          echo "Ddddocr test classification successful message found in log/gift_solver.txt!"
        fi
