name: Python application

on:
  push:
    branches: [ "main" ]
    paths:
      - '**.py'
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.py'
  release:
    types: [ "published" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12.x", "3.13.x"]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    
    - name: Setup python environments
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install script dependencies
      run: python3 main.py --autoupdate

    - name: Write bot token
      run: echo "${{ secrets.CI_BOT_TOKEN }}" > bot_token.txt
    
    - name: Run script and wait for activation message
      run: |
        python3 main.py --autoupdate | while read -r line; do
          echo "$line"
          if [[ "$line" == *"Activation messages sent to admin user"* ]]; then
            echo "Activation message detected, stopping script."
            break
          fi
        done